### ISSUE TITLE
Client 'Network Protocol Error' with No Chat Reports installed on the client

### ISSUE THREAD

**Issue by exalented** [Pumpkin-MC/Pumpkin#252]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

BTW, I run Arch Linux

### Server Software Version/Commit

https://github.com/Snowiiii/Pumpkin/commit/4067f65ff92057e4cbbf37ad03f64ce99d2076e9

### What happened?

1.21.1 Client with ViaFabricPlus & No chat reports / OpenJDK 23.0.1.u0-1.
```
[14:39:38] [Render thread/INFO]: Connecting to server, 25565
[14:39:40] [Render thread/ERROR]: Failed to handle packet class_7439[content=literal{user joined the game.}[style={color=yellow}], overlay=false]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_30349()" because "this.field_2062.field_1687" is null
	at knot/net.minecraft.class_338.localvar$cmp000$nochatreports$modifyGUIMessage(class_338.java:1629) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_338.method_44811(class_338.java:213) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_338.method_1812(class_338.java:208) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7594.method_44736(class_7594.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_634.method_43596(class_634.java:904) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7439.method_43631(class_7439.java:25) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7439.method_11054(class_7439.java:11) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[14:39:40] [Render thread/WARN]: Client disconnected with reason: Network Protocol Error
```
Uninstalling No Chat Reports fixes this issue and the client is able to join the server no problem.

### To Reproduce

1. Install No Chat Reports: https://modrinth.com/mod/qQyHxfxd
2. Join server.
3. Pumpkin logs that the player immediately leaves and error is thrown on the client above.

### Expected behavior

Join server without it throwing Network Protocol Error.

**Comment by Snowiiii** [comment]
Maybe its because Pumpkin currently does not initialize secure chat

**Comment by lucas11222** [comment]
> Maybe its because Pumpkin currently does not initialize secure chat

yea when i was in plugin developing if is null it chases

**Comment by DataM0del** [comment]
![image](https://github.com/user-attachments/assets/389e7ece-9650-45ae-8329-7bbd77650068)

**Comment by Snowiiii** [comment]
This seems to be fixed in https://github.com/Aizistral-Studios/No-Chat-Reports/commit/382977937ae8545455f53b6e54cde93b1a93ff7d
